StampyAI/stampy-ui

README.md
app/components/question.tsx
app/hooks/useQuestionStateInUrl.ts
app/root.css
app/routes/index.tsx
app/stampy.ts

Fixed link to http://ui.stampy.ai in README, shadows in Win Chrome, ... and added the pencil icon as a link to edit the answer on wiki (without popup yet, just a link that opens on new tab).

Small changes for ui.stampy.ai deployment

---

.github/workflows/gen-encodings-deploy.yml

Added trigger on PR close. Tested on my repo's main branch. Screenshot of run by 3 triggers: manual, scheduled, and PR merge/close. 
It doesn't seem to be called when a PR is closed without merging. I included in a couple checks to deploy only if encodings changed or a merge occurred. Might be harmless to remove and deploy even when no change... ie when scheduled. Anyway, left it there for you to decide how/which you want to use.

trigger on pr merge/close

---

.github/workflows/deploy.yml

Created a separate deploy action so we can deploy (manually or after PR merged/closed) until we figure out what's wrong with the failed push after generating encodings.

auto deploy

---

app/hooks/useQuestionStateInUrl.ts
app/root.css
app/routes/$.tsx
app/routes/index.tsx

When noLogo=true, the window title is set to "AI Safety FAQ", no colorful background shown, and place top icons in a row to minimize vertical space. As always, LMK if there's a better way to do this.
https://stampy-ui.ccstan99.workers.dev/?noLogo=true

Tweak title, background, icons for noLogo

---

.github/workflows/gen-encodings-deploy.yml
questions-encodings.mjs

@plexish @Aprillion I dug around a bit and I *think* the GitHub Actions for generating the embeddings was failing because the script doesn't have permission to push the generated embeddings to the protected main branch. According to (https://github.com/marketplace/actions/push-to-status-check-protected-branches), we might be able to work around this using PAT (personal access tokens). Since I don't have permission to do this, could one of you please:
(1) Create a PAT which grants the following scope/permission with admin write:repo_hook to stampy-ui (https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)
(2) Create a repository secret named "PAT_GEN_EMBEDDINGS" with the value of the PAT from the previous step …

fix GitHub Action to auto generate embeddings

---

.github/workflows/gen-encodings-deploy.yml

Oops, GH actions failing since email should be string not variable.
[Invalid workflow file: .github/workflows/gen-encodings-deploy.yml#L34](https://github.com/StampyAI/stampy-ui/actions/runs/3583544070/workflow)
The workflow is not valid. .github/workflows/gen-encodings-deploy.yml (Line: 34, Col: 14): Unexpected symbol: 'hello@stampy'. Located at position 1 within expression: hello@stampy.ai

fix typo in email

---

package.json

'**' was introduced in Bash 4, so older shells treat it as a simple "*". This results in only one level of folders being checked for files. See [this](https://medium.com/@jakubsynowiec/you-should-always-quote-your-globs-in-npm-scripts-621887a2a784) for more.

Make sure npm properly globs for older shells

---

app/root.tsx

Voting in https://discord.com/channels/677546901339504640/758062805810282526/1085884243328114740 - if the last option `D` with image on the side that takes the least amount of vertical space wins, this is the PR for it.

smaller logo for social media preview

---

app/components/dialog.tsx
app/hooks/useQuestionStateInUrl.ts
app/root.css

martinkunev#8534 on Discord reported a bug where an older version of firefox breaks when showing tags: https://discord.com/channels/677546901339504640/1088241479639646318
The reason for this bug is that his version of firefox (92) doesn't support HTML5 dialogs. This PR adds a fallback manual dialog thingy:
It could be made prettier, but I don't think it's worth the bother - most people will have more recent browsers

Handle dialogs in older browsers

---

app/routes/index.tsx

https://github.com/StampyAI/stampy-ui/issues/221
This is part of a potential solution.
I was initially considering transforming known gdoc links to relative links in the `stampy.ts` file (or something like that), but it's tricky, as both the list of questions to be displayed and the mapping of gdocs links -> pageids are fetched asynchronously. This means that either can be first, so you'd have to replace links both when the questions are fetched, and when the mapping is fetched. Which quickly gets ugly.
My proposed solution is to move the mapping into the parser. So the markdown will already have gdoc links replaced with the appropriate local links, e.g. `https://docs.google.com/document/d/1gKCatii1pXz53-7djMjP_YrBfvHcNVf0YDtDY1A6A0E/edit` gets transformed to `/?state=1234`. The nice …

[RFC] Handle relative links to questions

---

app/components/search.tsx
app/routes/questions/log.tsx

https://github.com/StampyAI/stampy-ui/issues/174
This is quite complicated, as I wanted to only log actual queries, rather than each button press. One way around this would be to only log stuff once the user presses enter, but I'm guessing that would massively limit the number of searches logged. So I settled on this, which amounts to:
* if the current search value is significantly different from the previous one (i.e. neither is a substring of the other), then log the search value
* if the search bar hasn't been changed for the last 4 seconds, log the search term, as the user has probably either found what they were looking for, or have given up

Log searches to the NLP endpoint

---

app/hooks/useQuestionStateInUrl.ts
app/root.css
app/routes/index.tsx
app/routes/questions/$question.tsx
app/routes/questions/allQuestionsOnSite.ts
app/routes/questions/answerDetailsOnSite.ts
app/routes/questions/cache.tsx
app/routes/questions/glossary.ts
app/routes/questions/search.tsx
app/server-utils/kv-cache.ts
app/server-utils/stampy.ts

Fixing #228 by passing `request` object to `withCache` so it's able to send `?reload` request.
Also improving the cache page (faster loading of page, showing only keys without values initially), see deployed on https://stampy-ui.aprillion.workers.dev/questions/cache.
And using data loaded in background where it makes sense (only for lazy features that wouldn't cause jumping of initial questions), so the current user benefits form the background data refresh too 😅

Cache invalidation fixes

---

app/routes/index.tsx
app/server-utils/stampy.ts

`clicking the arrows next to footnotes takes you all the way to the top of the webpage, rather than the top of the current question (regardless of how many questions are open)`
Each such bug makes me long for tests more. Some day that will go critical...

Fix footnote jumping

---

app/routes/[sitemap.xml].tsx
app/routes/questions/$question.tsx
app/server-utils/stampy.ts

https://github.com/StampyAI/stampy-ui/issues/272
Uses the new [glossary table](https://coda.io/d/AI-Safety-Info_dfau7sl2hmG/Glossary_suZVl#Glossary_tujmw)

Use glossary table

---

app/routes/random.tsx

https://github.com/StampyAI/stampy-ui/issues/295

random questions

---

app/routes/questions/$question.tsx

https://github.com/StampyAI/GDocsRelatedThings/issues/54
https://github.com/StampyAI/GDocsRelatedThings/issues/55
https://github.com/StampyAI/GDocsRelatedThings/issues/56

fix glossary bugs

---

app/hooks/useQuestionStateInUrl.ts
app/root.css
app/routes/questions/$question.tsx
app/server-utils/stampy.ts

https://github.com/StampyAI/stampy-ui/issues/292
This is just adds the basic functionality, without any decent colours or images (both of which can be set in Coda)

Add basic banner functionality

---

app/routes/questions/$question.tsx
app/routes/questions/glossary.ts
app/server-utils/responses.ts

The chatbot is playing about at proxying this, when it could just directly call it

Add CORS to /questions/$

---

app/server-utils/responses.ts

Sorry to keep bothering you with these :D

Allow localhost for CORS

---

README.md
app/components/search.tsx
app/hooks/useQuestionStateInUrl.ts
app/root.css
app/routes/index.tsx
app/routes/questions/$question.tsx
public/embed-example.html

Improvements for #307 => testing on https://aisafety.preview.softr.app/new
* can be controlled by `showDetails` url param
* I was not able to reproduce dynamic height in Softr, either CSP or it doesn't allow listening to events somehow, so this is a version more friendly for static height

Make links out of search results and question titles when embedded

---

README.md
app/components/layouts.tsx
app/components/search.tsx
app/hooks/search.tsx
app/hooks/useQuestionStateInUrl.ts
app/root.css
app/routes/index.tsx
public/tfWorker.js

Replacing feature from #303 to be able to share url to search results instead of just directly to answer.
Some fixes for URL state when overwriting search and using the browser back/forward buttons, seems good enough for this hidden feature, but probably not 100% bugfree yet 😅 
Testable in https://stampy-ui.aprillion.workers.dev/?q=why&limit=100

Support shareable url with search query (q and limit)

---

app/root.css

* use transition to keep hover while moving the mouse diagonally through margin
* reset color and font overriding inherited values from parent link
* https://stampy-ui.aprillion.workers.dev/

fix glossary popup styles

---

app/components/search.tsx
app/hooks/search.tsx
app/server-utils/kv-cache.ts

* running all of the intermediate searches was too slow, so the queue wasn't enough
* manually debouncing `searchLater()` to the latest query while a previous one is running works better for me
* https://stampy-ui.aprillion.workers.dev/

Search fixes

---

.github/workflows/deploy.yml

* actions after merging PRs from forked repos don't have access to GH secrets and fail => manual deploy is needed for those
* tested in https://github.com/StampyAI/stampy-ui/actions/runs/6423175192

Fix manual dispatch of deploy

---

app/root.css
app/routes/tags/$tag.tsx
app/routes/tags/index.tsx

https://github.com/StampyAI/stampy-ui/issues/329

Change tags buttons to links

---

app/root.css
app/routes/index.tsx
app/server-utils/parsing-utils.spec.ts
app/server-utils/parsing-utils.ts
app/server-utils/stampy.ts
public/assets/Icon_External_Link.svg

* fix #340 by making all links from the answers external
* remove the external link icon if we don't need to distinguish between 2 types of links
* https://stampy-ui.aprillion.workers.dev/

make all links from the answers external #340

---

.github/workflows/pr-check.yml

Removes the refresh of the coda data from the `pr-check` workflow, so that workflow can run from forked branches. Fixing #353 . 
Related to this PR, PR #356 adds a workflow to make is easier to refresh the cached data.

feat(refresh-coda-cache workflow): add workflow.

---

app/routes/$redirects.tsx
app/routes/help.tsx
app/server-utils/coda-urls.ts
app/server-utils/stampy.ts
remix.config.js

Maps redirects from [Coda](https://coda.io/d/AI-Safety-Info_dfau7sl2hmG/Redirects_suXjM#Redirects_tuOm3)

Coda configurable redirects

---

app/components/ArticlesDropdown/index.tsx
app/routes/tags.$tagId.$.tsx
app/routes/tags._index.tsx

This PR changes the route for tag pages from `tags/{tag name}` to `tags/{tag id}/{tag name}`.
Only tag id is needed to navigate to the page.

use tagId for tag routes

---

package-lock.json
package.json

I noticed that stampy.ts tests are failing (e.g. https://github.com/StampyAI/stampy-ui/actions/runs/7854687158/job/21435971107) with the following error:
```
app/server-utils/stampy.ts:196:45 - error TS2576: Property 'json' does not exist on type 'Response'. Did you mean to access the static member 'Response.json' instead?
196     json = await (await fetch(url, params)).json()
```
I think it is due to the types conflict described [here](https://github.com/cloudflare/workerd/issues/1298).
This PR removes `@types/node` to remove the conflict. This doesn't seem to break the app or any tests.

pin @node/types to 20.8.3

---

.eslintrc
app/routes/_index.tsx

* server-side redirect in remix loader
* no parser update yet (articles still have old links in the text)
* preserving `?question=...` url search param (not converting to title-in-url yet)

redirect ?state urls (#382 part 1)

---

app/components/CategoriesNav/Menu.tsx
app/components/SearchInput/Input.tsx
app/routes/tags.all.tsx

The placeholder text for the search input on the categories page should be "Filter by keyword"
This PR adds an optional prop to the `SearchInput` component to allow setting the placeholder text

feat(Input): add placeholder prop and set for Menu

---

app/newRoot.css

Trying to move the categories nav into the correct location. Relates to #379 
I did this by adding some margin
I think this matches figma now, but I'm not sure if `margin-left` on `.group-elements` is the best way to do this. Let me know your thoughts!

feat(newRoot.css): add margin-left to .group-elements

---

.github/workflows/deploy-dev.yml

I'm not sure how to best deploy a test version of the new site, so please criticize this

Deploy test env

---

app/components/Footer/footer.css
app/components/Footer/index.tsx
app/newRoot.css

finish footer styling

---

app/components/Article/Contents.tsx
app/components/Article/article.css
app/components/Button/button.css

Glossary css

---

app/routes/questions.$questionId.$.tsx

Fixes: #531 
From the figma, I think this colour should be `cool grey 900`
But from the css, `cool-grey-900` is defined [to be the same as black](https://github.com/StampyAI/stampy-ui/blob/master/app/newRoot.css#L6). And as [we have a class for black](https://github.com/StampyAI/stampy-ui/blob/dd1e10e185326fcbffbb4b9ef4abfbc3944bd4da/app/newRoot.css#L164) but no class for cool grey 900, I figured I would go ahead with adding the `black` class.
I tested fix on safari on Iphone (where I was able to reproduce this error previously).

fix(questions route): add black class to mobile nav button

---

.storybook/preview.tsx
package-lock.json
package.json

Fixes #452
Using RemixStub in order to provide necessary remix context https://blog.sentiero.digital/how-to-run-remix-link-component-in-storybook
Also, remove BrowserRouter as it was causing double router and isn't required for Remix https://remix.run/docs/en/main/guides/migrating-react-router-app#adapting-your-existing-app-code

chore(storybook preview): use RemixStub decorator

---

app/components/Chatbot/index.tsx
app/components/Feedback/Form.tsx
app/components/Menu/menuItem.css
app/components/Nav/nav.css
app/components/SearchResults/Dropdown.tsx
app/root.css

https://stampy-ui2.aprillion.workers.dev/

clean up fcol-x lefovers from merge

---

app/components/Article/Contents.tsx
app/components/Article/index.tsx
app/components/Chatbot/ChatEntry.tsx
app/components/Chatbot/chat_entry.css

I've improved the hint styling for human-written responses, but not the other part of this ticket which was about improving the padding/spacing for articles. From my understanding, the styling for articles is done through some magic which converts google docs pages into well styled html. I think the way to fix spacing here is just to add/remove spaces in the docs

Ticket #376

---

app/components/Chatbot/ChatEntry.tsx
app/components/Chatbot/chat_entry.css
app/components/Chatbot/index.tsx

Ok so I think I've done it, except its a little bit janky. i.e. in order to get the height consistent and correct, instead of editing the dangerouslyPastedHTML I've just set the overflow: hidden, and set the height of the contents div to be one which generally doesn't seem to clip words. 
also, @melissasamworth I made a design decision to put the reference popup below the number (instead of above, which is on the figma), because I feel like it generally clips off less often because I notice I am more likely to be reading stuff at the top of the screen. I also like that the curser is closer to the title and link when its below. Anywho, I can change it if you disagree.
https://github.com/StampyAI/stampy-ui/assets/148247390/c8f3070f-706e-4456-97cf-4ab6180a28bb

Ticket-#597 - Reference Hover

---

app/components/Chatbot/index.tsx
app/routes/chat.tsx

Instead of messing with `onQuestion`, I decided to just use your `showFollowup` function at times when the pageId is available. e.i. followups, splash screen, and suggestions (I've renamed it to `showArticleByID` as such)  It seems to work great and its way faster now.

search by pageid instead of question

---

app/components/Chatbot/ChatEntry.tsx
app/components/Chatbot/chat_entry.css
app/components/Feedback/Form.tsx
app/components/Feedback/feedback.css
app/routes/chat.tsx

Fixed mobile feedback, left aligned human-written-response, z-index fix

miscellaneous mobile fixes

---

app/components/search.tsx
app/routes/questions.toc.ts

@Aprillion you're right, of course :/

better handling of state in search

---

app/components/Article/index.tsx
app/routes/questions.$questionId.$.tsx

* fix #753
* deployed in https://stampy-ui2.aprillion.workers.dev/questions/NM1D - without in-progress banner if it's a subsection, https://stampy-ui2.aprillion.workers.dev/questions/8YFC still with the banner

hide in-progress banner in sub-sections #753

---

app/components/Article/KeepGoing/index.tsx

* #755 
* https://stampy-ui2.aprillion.workers.dev/questions/8TJV/How-can-I-help

use list table in section and subsections, but not articles #755

---

app/components/Article/KeepGoing/index.tsx
app/components/Article/index.tsx

* #757
* https://stampy-ui2.aprillion.workers.dev/questions/NLZV/

use list table in all sub-sections

---

app/components/ContentBox/index.tsx

I still think ideally the title should be fetched from the page directlly and not specified here

Update frontpage suggestions.

---

app/components/HowCanIHelp/HelpMethods.tsx
app/root.css

The only thing I couldn't figure out is making the layout like this on build your knowledge and join a community (help)

Footer fixes

---

app/routes/how-can-i-help.community.tsx

As with my other PR, the lint fails.
Here are the TODOs that are left
{/* TODO make this only appear in left part of page */}
{/* TODO make this only appear in left part of page */}
{/* TODO there seems to be lacking text or a link in the figma */}
// TODO: do we want to link to a specific tag here?

Murphant community 1

---

app/components/Article/Contents.tsx
app/components/Article/article.css
app/server-utils/parsing-utils.ts
app/server-utils/stampy.ts

The feature has been broken for a while, the text was simply ignored by the parser. I have removed what I believe is all traces of it in the backend.
I have also made sure there are no articles (live or not) that contain the text **[See more** so we should not see any instances of this text showing up on the site. It has also been removed from all of our documentation.
There might be some legacy code to remove from GDocsRelatedThings, but if this is the case, I could not find it.

Remove [See more...] from backend

---

app/components/Grid/index.tsx

To address https://github.com/StampyAI/stampy-ui/issues/553
This is just a short-term fix, I think we might benefit from using icons instead of AI-generated images (see https://github.com/StampyAI/stampy-ui/issues/674), I might experiment with that.

Update advanced image ratio to 72x72

---

README.md
app/components/Article/index.tsx
app/components/ArticlesNav/ArticleNavManualList.tsx
app/components/ArticlesNav/articlenav.css
app/routes/questions.$questionId.$.tsx

* support manual list of ids like https://stampy-ui2.aprillion.workers.dev/questions/NM25/?list=NM25,9FQK,NM1S,8PYV
* discussed in https://discord.com/channels/677546901339504640/1125883086849188041/1309262887033901084
* on top of PR #855

support `/questions/1?list=1,2,3` manual list of ids

---

app/server-utils/stampy.ts

clean up redirects as returned from coda - this fill fix the issue with redirects being broken now.
Coda sometimes returns values wrapped with "```", so this will strip that from links

clean up redirects

---

app/root.css
public/assets/Icon_External_Link.svg

fixes https://github.com/StampyAI/stampy-ui/issues/863
There were a few modifications compared to what was done in https://github.com/StampyAI/stampy-ui/pull/346, which Claude says give better compatibility, but @Aprillion LMK if it's wrong

Add icon to external links

---

README.md
package.json

I recently helped Algon setup a dev environment on his machine, I updated the README based on difficulties we had.
In particular, installing on a Windows machine had issues with quotes with this line
`"start": "remix dev --manual -c 'wrangler dev ./build/index.js'",`
I updated it based on a Claude suggestion to make it cross-platform, but I have not tested it.

Update README and installation

---

app/components/Footer/index.tsx

As requested by Vishaka and @Algon-33 based on a prompt by Ashgro
Algon has approved what it looks like.

Move "About us" to under "Get involved"

---

app/components/Article/Contents.tsx

fix https://github.com/StampyAI/stampy-ui/issues/923
It turns out that there was em-dash and quote replacement that was meant to normalize the glossary but applied even if there were not glossary hits. This led to seemingly random replacement of em-dashes to hyphen that would change upon refresh, which has annoyed @srkaas [for](https://discord.com/channels/677546901339504640/1125883308979535922/1300700976763899924) some [time](https://discord.com/channels/677546901339504640/1209956074984181830/1221869562035699774)

Update glossary to no longer replace text if there are no replacements necessary

---

app/components/Chatbot/index.tsx

This PR prevents a chatbot question from being submitted when the question text is empty.
This addresses https://github.com/StampyAI/stampy-chat/issues/140 because the current UI behaviour is that the question text box is cleared when the submit button is clicked. So, with this change, a double click doesn't cause an issue because the text box is empty after the first submit so the second click on the submit button has no effect.
Submitting an empty query does seem to have any value currently as it just leads to the model commenting on its system prompt

feat(Chatbot): disable submit on empty question

---

app/components/Article/article.css

Fix https://github.com/StampyAI/stampy-ui/issues/613
Addresses spacing of list items. I also shrank the spacing between lines inside list items, IMO it makes it more readable.
The best way to test this is to actually run it in the dev environment, but here are a few screenshots
https://aisafety.info/questions/8185/What-is-Goodhart's-law
https://aisafety.info/questions/NM38/4:-The-road-from-human-level-to-superintelligent-AI-may-be-short
https://aisafety.info/questions/3485/What-are-accident-and-misuse-risks

Improve list paragraph spacing

---

app/components/Article/article.css
app/components/MediaCarousel/index.tsx
app/components/MediaCarousel/mediacarousel.css

Fix https://github.com/StampyAI/stampy-ui/issues/930
Ended up not centering, but using margins as discussed.
Stretch images to text width minus 40px
Harmonize with MediaCarousel
Slightly reduce spacing around MediaCarousel navigation arrows
Non-carousel:
Within carousel:

Standardize image size and captioning

---

app/components/Grid/index.tsx

fix https://github.com/StampyAI/stampy-ui/issues/841
I just removed the images

Remove images for Advanced sections on Frontpage

---

app/components/Article/Contents.tsx
app/components/Article/article.css

Centred the article tables, added a border, green shading to the top row, min column widths and a horizontal scroll bar for when it looks too long. For Issue 586 https://github.com/StampyAI/stampy-ui/issues/586#issuecomment-3293162740

feat: Improve article table styling and responsiveness
