StampyAI/stampy-ui

.gitignore, README.md, wrangler.toml.template
Making this repo more friendly for multiple developers, added instructions to README - let me know if those make sense.
=> gitignore wrangler.toml and use a template

README.md, app/components/search.tsx, app/entry.server.tsx, app/root.css, package-lock.json, package.json, public/tfWorker.js, server.js, wrangler.toml.template
Moved Tensorflow initialization & search to web worker to avoid GUI blocking.
Updated README instructions
=> moved tf calls to web worker

app/components/question.tsx, app/components/search.tsx, app/hooks/useQuestionStateInUrl.ts, app/root.css, app/routes/index.tsx, app/stampy.ts, public/tfWorker.js
=> Clickable search results

app/components/search.tsx, app/hooks/useQuestionStateInUrl.ts, app/root.css, app/routes/index.tsx
* clicking on the same search results multiple times will move it to the top position only once
=> make search selection idempotent to fix #53

app/root.css
* keep desktop scrolling on html element, not body
=> fix #65 apply the fix of #45 only to mobile size screens

.github/workflows/gen-encodings-deploy.yml
* we want to require pull requests for master branch,
but also allow pushing changes from the action
=> force push from github action

app/components/question.tsx, app/components/search.tsx, app/hooks/useQuestionStateInUrl.ts, app/routes/index.tsx, app/routes/questions/$question.ts, app/routes/questions/allCanonicallyAnswered.ts, app/server-utils/kv-cache.ts, app/server-utils/stampy.ts, app/stampy.ts, package-lock.json, package.json
Fixing #29 and related bugs I noticed while changing the cache.
=> Caching in background

app/root.css
Added more styling on answer tables. Updated color scheme in dark mode to match https://safetyai.org/ in preparation for more "serious" look. Styled search dropdown menu.
=> More styling

app/components/copyLink.tsx, app/components/question.tsx, app/root.css, app/routes/index.tsx
=> Fix search icon and copy link

app/root.tsx
Tested on my  dev cloudflare with great success
=> Added hotjar

app/components/search.tsx, app/hooks/useQuestionStateInUrl.ts, app/root.css, app/routes/index.tsx
Fixed a couple of issues and added a "noLogo" option for when a more serious look is needed. I piggybacked off of the useQuestionStateInUrl function, so LMK if it should be moved elsewhere.
Sample test preview
https://stampy-ui.ccstan99.workers.dev/?noLogo=true
=> No logo & small fixes

.github/workflows/gen-encodings-deploy.yml
Scheduled cron job to generate encodings at midnight & noon UTC daily
=> generate encodings 2x daily

.github/workflows/deploy.yml, app/routes/$.tsx
we are experiencing strange issues with wrong mime type when deployed from GH actions, while the same code works fine when deployed from my local computer => adding some debug info to GH action as per advice from https://twitter.com/GregBrimble/status/1587138240254967808
=> debug CF issues

app/components/search.tsx, app/root.css
The button is an anchor link to `https://stampy.ai/wiki/Special:FormStart?form=Q&page_name=${searchInput}`. This opens the form for adding a new question.
=> add button to request exact question

.github/workflows/deploy.yml, .github/workflows/gen-encodings-deploy.yml
Trying to address 2 failed GH actions
=> Fix GH actions

.github/workflows/deploy.yml
* do not deploy when closed by rejecting PR and not from other target branches
=> Deploy only from merged PR to master

.github/workflows/deploy.yml
=> fix github action

.github/workflows/deploy.yml, .github/workflows/gen-encodings-deploy.yml, README.md, app/components/search.tsx, app/root.css, app/routes/questions/add.tsx, app/routes/questions/all.tsx, app/server-utils/stampy.ts, wrangler.toml.template
* fixes bug with sugestions list not being navigable by keyboard
=> Add new questions when none match

app/components/dialog.tsx, app/components/tags.tsx, app/root.css, app/routes/index.tsx, app/routes/questions/$question.tsx, app/routes/questions/add.tsx, app/server-utils/stampy.ts
=> Display tags for questions

app/server-utils/stampy.ts
=> fix loading by alphanumeric question id #150

app/components/infiniteScroll.tsx, app/hooks/useQuestionStateInUrl.ts, app/root.css, app/routes/index.tsx, app/routes/questions/allOnSite.ts, app/server-utils/stampy.ts
I added a loader type thingy, but left the footer for now
=> Add infini-scroll

app/components/search.tsx, app/root.css, app/routes/index.tsx, app/routes/questions/add.tsx
https://github.com/StampyAI/stampy-ui/issues/144
=> Fix Safari bug in search

app/hooks/stateModifiers.tsx, app/hooks/useQuestionStateInUrl.ts, app/routes/index.tsx
https://github.com/StampyAI/stampy-ui/issues/161
https://github.com/StampyAI/stampy-ui/issues/160
=> Fix url bugs

app/routes/index.tsx, app/routes/questions/$question.tsx
https://github.com/StampyAI/stampy-ui/issues/165
=> Allow edit links to be clicked

app/routes/questions/$question.tsx, app/server-utils/stampy.ts
https://github.com/StampyAI/stampy-ui/issues/164
=> handle unknown pageids

app/components/errorHandling.tsx, app/root.tsx, app/routes/index.tsx
Per question errors:
When something goes wrong on the server:
=> Add ErrorBoundary for questions

app/routes/questions/$question.tsx
https://github.com/StampyAI/stampy-ui/issues/59
=> Better text for empty answers

app/routes/index.tsx, app/server-utils/stampy.ts
https://github.com/StampyAI/stampy-ui/issues/79
=> Hide everything after [See more...]

app/root.css, app/routes/index.tsx, app/routes/questions/$question.tsx, app/server-utils/stampy.ts
https://github.com/StampyAI/stampy-ui/issues/180
to this
=> Format [Show more...] as link

app/components/search.tsx, app/root.css
https://github.com/StampyAI/stampy-ui/issues/187
=> Ensure new questions dialog has min width

app/components/search.tsx, app/root.css, app/server-utils/stampy.ts, app/server-utils/url-to-iframe.ts
https://github.com/StampyAI/stampy-ui/issues/183
When nothing loaded:
When questions present:
=> Loading for search

app/hooks/useQuestionStateInUrl.ts, app/routes/questions/$question.tsx
Add logic to add the string 'WIP - ' to any question that does not have the staus of 'Live on site'.
=> Append WIP to unpublished questions

app/components/infiniteScroll.tsx, app/root.css, app/root.tsx, app/routes/index.tsx, app/server-utils/kv-cache.ts, package-lock.json
* npm audit fix
* use fun logo on stampy.ai top domain, fixes #157
* make infinite scroll less trigger happy
* load only if user actually scrolls (for direct links to a question that have small content)
* preserve url parameters in cache reload
* stop reloading all pages when the last one is reached
=> Fun logo on stampy.ai,  inifinite scroll less trigger happy

app/hooks/useQuestionStateInUrl.ts, app/root.css, app/routes/index.tsx, app/routes/questions/$question.tsx, app/routes/questions/allQuestionsOnSite.ts, app/routes/questions/answerDetailsOnSite.ts, app/server-utils/stampy.ts, package.json
=> Fix double scroll on mobile and related questions filter

app/hooks/stateModifiers.tsx, app/hooks/useQuestionStateInUrl.ts
=> load related questions for direct links

app/hooks/stateModifiers.tsx, app/hooks/useQuestionStateInUrl.ts, app/root.tsx
https://github.com/StampyAI/stampy-ui/issues/209
=> 209: Social preview of link that includes related ids

app/hooks/useQuestionStateInUrl.ts
=> Show only onSite related questions

app/components/search.tsx, app/root.css
* fix #215
* don't immediately post suggestion when there is error fetching extra questions
* show `no results` message when plaintext search returns empty array
=> Use keyword search for up to 2 words

app/components/search.tsx, app/routes/questions/search.tsx
https://github.com/StampyAI/stampy-ui/issues/217
=> Catch errors from search endpoint

app/root.css, app/routes/questions/search.tsx, package-lock.json
=> Fit unanswered dialog on mobile screens

app/root.css, app/routes/questions/$question.tsx
https://github.com/StampyAI/stampy-ui/issues/239
=> Popup links

app/root.css, app/server-utils/stampy.ts
https://github.com/StampyAI/stampy-ui/issues/238
=> Show "See less" after toggling more

app/routes/questions/$question.tsx, app/server-utils/kv-cache.ts
* https://github.com/StampyAI/stampy-ui/issues/257
* Handle glossary items in urls. https://aisafety.info/?state=0_ has been updated to add more test cases
=> Better handling of gloasary items in links

package-lock.json, package.json
* fix #274 - library updated to detect `load` event of images and iframes to recalculate the height afterwards
=> update react-auto-height 

app/hooks/search.tsx
addressing https://github.com/StampyAI/stampy-ui/issues/246#issuecomment-1650191009
=> boost "What is ..." questions in baseline search results

app/hooks/useQuestionStateInUrl.ts, app/routes/questions/allQuestionsOnSite.ts, app/routes/questions/answerDetailsOnSite.ts, app/routes/questions/editors.tsx, app/server-utils/stampy.ts
https://github.com/StampyAI/stampy-ui/issues/290
This collects the hidden functionality in a single, also hidden functionality. I'm not at all sure whether this is a good idea, though...
=> Add page for editors

app/server-utils/stampy.ts
https://github.com/StampyAI/stampy-ui/issues/294
=> Make sure the tags are loaded when fetching questions contents

app/routes/questions/$question.tsx
The banners are always shown now - this will put them in the questions fold
=> Fix banners position

app/root.css, app/root.tsx, public/embed-example.html
fix for dynamic height, testing on https://aisafety.softr.app/new-stampy
(advice from ChatGPT 4 helped 😅)
=> iframe dynamic height using postMessage

app/root.css
* hotfix for #312
* seems like I made a mistake in https://github.com/StampyAI/stampy-ui/commit/f914c073c6db0517818dacdab82b86e416145522#r126940265, no idea how 🤦
=> fix see more toggle inside amswers

app/server-utils/parsing-utils.ts
* fixing #323 where invalid HTML caused server-side and client-side render mismatch and double-rendering of question footer
=> fix HTML around see-more

app/components/search.tsx, app/hooks/search.tsx, app/root.css, app/server-utils/stampy.ts
* fixing #321
* e.g. https://stampy-ui.aprillion.workers.dev/?q=simply
=> add alternate phrasings to base search

app/root.css
=> remove max-width and padding for embed, giving control to parent page

app/components/search.tsx, app/routes/questions/$question.tsx
* fix #339 
* fix #338
Deployed to https://stampy-ui.aprillion.workers.dev/
=> Dedupe glossary and update placeholder

app/routes/random.tsx
Rob wanted the random page to work as a redirect
=> random redirects to random question

.gitignore, app/routes/questions/add.tsx, package-lock.json, package.json, remix.config.js
* `npm audit fix`
* uptate remix to make it work again
* fix TS
... `rm -rf node_modules` might be needed, not sure since I tried to update too much stuff that broke everything and I had to start again ... works on my machine and on https://stampy-ui.aprillion.workers.dev/ so the committed changes should be fine 🤞
=> npm audit fix

app/routes/help.tsx
https://discord.com/channels/677546901339504640/1125882087908573305/1201556316481671280
=> Redirect from /help

app/components/Footer/index.tsx, app/newRoot.css
I ran the lint, now I'm committing my changes, then I'll push to my current branch, then I'll make a pull request and ask Nemo to review, then I'll merge it with stampy-redesign.
=> Footer CSS fixes

app/components/Article/article.css, app/components/CategoriesNav/Menu.tsx, app/components/CategoriesNav/menu.module.css, app/components/Nav/nav.css, app/components/SearchInput/input.css, app/components/Table/index.tsx, app/newRoot.css, app/routes/$questionId.tsx, app/routes/tags.$.tsx
=> tags styling

app/components/ArticlesNav/menu.css
=> fix(menu.css): remove disclosure triangle for webkit browser

app/components/Chatbot/ChatEntry.tsx, app/components/Chatbot/chat_entry.css, app/components/Chatbot/index.tsx, app/hooks/useChat.ts, app/hooks/useGlossary.ts, app/root.css, app/root.tsx, app/routes/questions.$questionId.$.tsx
=> human answers

app/components/Article/FeedbackForm/index.tsx, app/components/ArticlesDropdown/index.tsx, app/components/ArticlesNav/articlenav.css, app/components/CategoriesNav/Page.tsx, app/components/Error/index.tsx, app/components/Footer/index.tsx, app/components/SearchResults/Dropdown.tsx, app/components/Widget/Stampy.tsx, app/newRoot.css, app/routes/_index.tsx, app/routes/categories.$.tsx
* in the spirit of previous `.col-x` classes with 12 columns, but should be compatible with `body {max-width: ...}` now
* https://stampy-ui2.aprillion.workers.dev/
=> reintroduce vw-based .col-x

app/components/Chatbot/index.tsx, app/components/Chatbot/widgit.css, app/components/Input/input.css
Added white space under input, and fixed positioning i.e. the chat input is relative to the viewport for both the chatbot view and main page
=> Ticket #591

app/components/Button/button.css, app/components/Button/index.tsx, app/components/Chatbot/ChatEntry.tsx, app/components/Chatbot/chat_entry.css, app/components/Chatbot/index.tsx, app/components/Chatbot/widgit.css, app/root.css
=> formatting chat messages, typo fix

app/root.css
This reverts commit 195edbdd4c5aecbe2a3455d1da7f26cd6d575186.
=> Revert "Updated grid"

app/components/Feedback/index.tsx, app/routes/questions.actions.tsx
Ik its not the prettiest, but it is certainly the most efficient :)
=> Ticket #695

app/hooks/useChat.ts
It turns out that chrome has a relatively low limit on the amount of data that can be sent with `fetch`...
=> fix chrome bug

app/components/SearchInput/Input.tsx, app/components/SearchInput/input.css
Fixing #741
https://stampy-ui2.aprillion.workers.dev/
=> fix search collapsing before click

app/routes/editors.tsx
=> Added tools section to EditorHelpers page

app/components/Article/KeepGoing/index.tsx, app/components/Button/button.css, app/components/Button/index.tsx, app/components/Chatbot/index.tsx, app/components/Input/input.css, app/components/Table/index.tsx, app/root.css
So I've made the text smaller and I think it looks alright but I encourage people to test it out on different browsers / OS. 
https://github.com/user-attachments/assets/5ad6ae34-29b3-48ec-985f-b001d97cd31d
=> Smaller text & Internal Links in Section Overview open in same tab

app/components/HowCanIHelp/CatgoryCarousel.tsx, app/components/HowCanIHelp/HelpItem.tsx, app/hooks/useToC.tsx, app/routes/how-can-i-help.career.tsx, app/routes/how-can-i-help.donate.tsx
=> fix Carousel + add tags to HelpItem

app/root.css, app/routes/how-can-i-help.career.tsx
=> Smooth scroll only on career

app/components/icons-generated/GovermentBuilding.tsx, app/components/icons-generated/Microscope.tsx, app/components/icons-generated/PuzzlePieces.tsx, app/routes/how-can-i-help.knowledge.tsx
Everything that's not done is marked with "TODO" in the code
=> Murphant knowledge2

app/components/CategoriesNav/categoriesnav.css
Ref https://github.com/StampyAI/stampy-ui/issues/521
=> Reduce spacing between categories

app/components/ArticlesDropdown/index.tsx
This works, but is extremely duct-tape-y since the things that appear in the Table of Contents should usually be questions. If there are more such entries in the ToC in the future we will want to refactor this.
@mruwnik if you have a better way to do this, feel free to reject this PR and do it
=> Update Table of Content

app/components/Article/article.css, app/components/HowCanIHelp/Base.tsx, app/components/HowCanIHelp/howcanihelp.css
=> Sundry fixes

app/routes/questions.$questionId.$.tsx
* send a defered error message from loader to client (no point creating `new Response()` inside the deferred Promise on the client)
* https://stampy-ui2.aprillion.workers.dev/questions/bla
=> improve error handling for not found ID

app/components/Article/article.css
To address https://github.com/StampyAI/stampy-ui/issues/862
=> Reduce footnote size to 14px

app/hooks/useCachedObjects.tsx, app/hooks/useToC.tsx, app/routes/questions.toc.ts, stories/ArticlesKeepGoing.stories.tsx
Should fix [this bug](https://github.com/StampyAI/stampy-ui/issues/868)
=> fix ToC bug

app/components/Article/article.css
* simplified implementation of styles from https://github.com/StampyAI/stampy-ui/pull/853/files#diff-305ca81b45f5d72d60710d2591d6923fa79a1be1497d6ef9fe739d74251608b8
* deployed in https://stampy-ui2.aprillion.workers.dev/questions/98OW for testing
=> blockquote styles

app/components/HowCanIHelp/howcanihelp.css, app/routes/how-can-i-help._index.tsx
Aiming to fix this break in the title of the How Can I Help section on mobile:
=> Fixed random mobile line break

app/components/ContentBox/index.tsx
eventual TODO: Fetch these titles automatically
=> Update frontpage article title

app/components/ArticlesDropdown/index.tsx
This reverts commit 33a8ab35c03678c472af813863eb2b29222733c6.
As requested at https://discord.com/channels/677546901339504640/1193299418259140690/1338363741124821004
This is good since this commit was very duct-tape-y
=> Revert "Make special case in ToC for how-can-i-help"

app/components/Article/Contents.tsx, app/components/Article/article.css
* fixes #766
* https://stampy-ui2.aprillion.workers.dev/questions/NM1M/
=> center images and captions

app/routes/questions.toc.ts
As requested by @srkaas 
Tested, works as expected.
=> Make items with no order go last in ToC

.github/workflows/issue-to-project.yml
Add new issues to https://github.com/orgs/StampyAI/projects/1 automatically
=> Add new issues to project 1

app/root.css, app/routes/_index.tsx
Fixes https://github.com/StampyAI/stampy-ui/issues/913
=> Murphant 913 replace h1

app/components/Article/Contents.tsx
Fix
https://github.com/StampyAI/stampy-ui/issues/861
=> Ignore glossary if it's in a link

app/components/ContentBox/index.tsx
fixes https://github.com/StampyAI/stampy-ui/issues/922
=> Update frontpage for issue 992

app/components/Article/Contents.tsx, app/components/Article/article.css, app/components/Article/index.tsx, app/components/MediaCarousel/index.tsx, app/components/MediaCarousel/mediacarousel.css, app/server-utils/parsing-utils.ts
Updated for the first carousel on [this page](https://aisafety.info/questions/NM3T/The-Basic-Case-for-AI-Safety)
You can see the result in the Carousel section at the bottom of [Examples with all the formatting](https://aisafety.info/questions/0)
Works both for videos and images
=> Support embedding Google Drive videos in Carousel

app/components/Article/Contents.tsx
Fix https://github.com/StampyAI/stampy-ui/issues/920
Make https://github.com/StampyAI/stampy-ui/issues/919 more robust
Also centralized HTML conditions to exempt from Glossary
=> Exclude entries from Glossary

app/components/SearchInput/input.css
Before:
https://github.com/user-attachments/assets/1bca47f5-703b-4da3-bae3-87bf5052fa69
After:
https://github.com/user-attachments/assets/9bad47bb-cfb9-4241-8c9d-6f7916ef36eb
=> Fix search bar on mobile

app/components/Article/Contents.tsx
Fix https://github.com/StampyAI/stampy-ui/issues/928
=> Ensure the original glossary text is kept

app/routes/cache.tsx, app/routesMapper.ts
Allows clearing of a single cache entry (e.g. banners).
Fixes the Cache page in development environments.
Pretty-prints values
Pre-fetches titles for article IDs (Algon's request)
=> Cache page improvements

app/components/Article/article.css
Fix https://github.com/StampyAI/stampy-ui/issues/946
=> Add spacing under headers

app/routes/cache.tsx
Remove titles from cache as discussed here https://github.com/StampyAI/stampy-ui/pull/942#discussion_r2083944633
=> Remove title fetching from cache

app/components/ContentBox/index.tsx, app/routes/_index.tsx
=> Changed text in front page boxes

app/components/ArticlesNav/articlenav.css
Fix https://github.com/StampyAI/stampy-ui/issues/857
Video:
[scrolling_bar.zip](https://github.com/user-attachments/files/20418508/scrolling_bar.zip)
=> Make ToC sticky

app/components/ArticlesDropdown/index.tsx, app/routes/questions.toc.ts, stories/ArticlesKeepGoing.stories.tsx, stories/MobileNav.stories.tsx
fix https://github.com/StampyAI/stampy-ui/issues/951
=> Change "Introductory" tag to "Basic"

app/components/Article/article.css
=> Make links in banner underlined for visibility

app/components/Article/article.css
=> fix firefox css

app/routes/how-can-i-help.grassroots.tsx
Requested by dasSpieler, approved by Bryce
https://discord.com/channels/677546901339504640/1088468403406258196/1408965202392776845
=> Change HCIH email template timer from 8m to 4m

app/components/Nav/Mobile/index.tsx
Fix https://github.com/StampyAI/stampy-ui/issues/984#event-19323701594
=> Add HCIH to mobile nav
